### ISSUE TITLE
Future of this fork

### ISSUE THREAD

**Issue by keynmol** [getnelson/quiver#4]
Howdy!

Is this fork going to be the officially maintained version? I'm asking because I'm doing some work on the following:

- Drop 2.11, publish for 2.12 and 2.13
- Move build to simpler multi-module
- Publish all modules for Scala.js 1.x
- Update all the dependencies
- Move from tut to mdoc
- Add scalafmt plugin
- Change site to sbt-microsites (couldn't get `sbt-site` to work with mdoc)

I have all of this working locally already, there's just some open questions about the site and publishing information.

Only asking to make sure that there's plans/credentials to publish new versions, or whether I should just maintain my own fork :)

**Comment by rossabaker** [comment]
Hi, thanks for your interest!  

The org in the build is still `io.verizon.quiver`.  It will need to be updated to `io.getnelson.quiver` to start publishing again.  I think all projects in this org are published from CI.  (That's definitely what we did in the Verizon Era.)  I think we'd need @timperrett's help with that, but I'm happy to help with reviews.

**Comment by keynmol** [comment]
How do folks feel about `sbt-ci-release` instead of archived `sbt-rig` for publishing?

I'm asking because I went full throttle changing things fully expecting to publish myself, but I can revert it back if the setup for `sbt-rig` still works?

I will push the WIP branch today so we can have something more concrete to talk about

**Comment by timperrett** [comment]
@keynmol I have automatic publishing setup on most of the other repos, i'm not familiar with sbt-ci-release or what the expectations are for that plugin (been out of the scala loop for a while now). If its sbt-rig then i can get this quickly published as it'll be the same setup I already have for the other nelson dependencies. If its sbt-ci-release i'd have to carve out some time to look at it; not sure when that would be 🙂

**Comment by keynmol** [comment]
> If its sbt-ci-release i'd have to carve out some time to look at it; not sure when that would be 🙂

That's good enough of an explanation why not do it :) I'll try to get this part of the build back in the same state then.
